name: update-job
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  kom-update:
    runs-on: ubuntu-latest
    steps:
      - name: Update Database
        run: |
          response=$(curl -s -X GET ${{secrets.UPDATE_URL}} \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{secrets.UPDATE_KEY}}")

          echo "API Response: $response"
